/**
 * Global high-intent SEO keyword set.
 */

// Global keywords for the application - Updated with AnswerThePublic high-volume keywords
export const globalKeywords = [
  'sorting algorithms',
  'sorting algorithm visualizer',
  'sorting algorithms time complexity',
  'sorting algorithms animation',
  'sorting algorithms visualization',
  'sorting algorithms for beginners',
  'sorting algorithms examples',
  'sorting algorithms cheat sheet',
  'sorting visualizer',
  'algorithm visualizer',
  'dsa sorting',
  'data structures and algorithms',
  'algorithm animation',
  'computer science education',
  'programming tutorial',
  'sorting algorithm comparison',
  'interactive learning',
  'algorithm complexity',
  'sorting performance',
  'coding interview prep',
  'algorithm practice',
  'programming education',
  'software engineering',
  'algorithm tutorial',
  'data structure visualization',
  'sorting techniques',
  'algorithm analysis',
  'computational thinking',
  'programming concepts',
  'algorithm implementation',
  'sorting algorithm tutorial',
  'algorithm learning tool',
  'interactive algorithm visualization',
  'sorting algorithm animation',
  'algorithm step by step',
  'sorting algorithm explained',
  'algorithm education platform',
];
