// Fast keyword detection for instant responses
export const FAST_KEYWORDS = {
  support: ['support', 'donate', 'sponsor', 'coffee', 'buy me', 'funding'],
  creator: [
    'creator',
    'author',
    'developer',
    'made by',
    'who made',
    'prabal',
    'alienx',
  ],
  github: ['github', 'repo', 'repository', 'source code', 'source'],
  help: [
    'help',
    'hi',
    'hello',
    'hey',
    'hola',
    '你好',
    '您好',
    'नमस्ते',
    'bonjour',
    'salut',
    'hallo',
    'guten tag',
    'ciao',
    'こんにちは',
    'こんばんは',
    'ওহে',
    'হ্যালো',
    'namaste',
    'what can you do',
    'commands',
  ],
  thankYou: ['thank', 'thanks', 'thx', 'tysm', 'thank you'],
  code: [
    'code',
    'implementation',
    'example',
    'show me code',
    'programming',
    'syntax',
    'show code',
    'code example',
    'source code',
    'implementation',
    'write code',
    'generate code',
  ],
};
export const KEYWORDS = {
  github: ['github', 'repo', 'repository', 'source code', 'source'],
  thankYou: ['thank', 'thanks', 'thx', 'tysm', 'thank you'],
  quadratic: ['n^2', 'n2', 'o(n2)', 'o(n^2)', 'quadratic', 'square time'],
  developer: [
    'developer',
    'creator',
    'author',
    'who made',
    'who created',
    'alienx',
    'prabal',
    'core developer',
  ],
  support: [
    'donate',
    'support',
    'sponsor',
    'coffee',
    'contribution',
    'help project',
  ],
  bubbleSort: ['bubble sort', 'bubble', 'bubblesort'],
  mergeSort: ['merge sort', 'merge', 'mergesort'],
  quickSort: ['quick sort', 'quick', 'quicksort'],
  heapSort: ['heap sort', 'heap', 'heapsort'],
  insertionSort: ['insertion sort', 'insertion', 'insertionsort'],
  selectionSort: ['selection sort', 'selection', 'selectionsort'],
  radixSort: ['radix sort', 'radix', 'radixsort'],
  bucketSort: ['bucket sort', 'bucket', 'bucketsort'],
  complexity: [
    'complexity',
    'time complexity',
    'space complexity',
    'big o',
    'o(n)',
    'performance',
    'efficiency',
    'speed',
    'fast',
    'slow',
  ],
  howItWorks: [
    'how does',
    'how it works',
    'explain',
    'what is',
    'algorithm works',
    'how',
    'work',
    'mechanism',
    'process',
  ],
  comparison: [
    'compare',
    'difference',
    'vs',
    'versus',
    'better',
    'faster',
    'slower',
    'which is',
    'pros and cons',
    'advantages',
    'disadvantages',
  ],
  steps: [
    'steps',
    'process',
    'procedure',
    'how to',
    'algorithm',
    'step by step',
  ],
  current: ['this', 'current', 'what is this', 'tell me about this', 'now'],
  general: ['hello', 'hi', 'hey', 'help', 'what can you do'],
  examples: ['example', 'demo', 'show me', 'demonstrate', 'sample'],
  visualization: ['visualize', 'visual', 'animation', 'see', 'watch', 'demo'],
  beginner: ['beginner', 'basic', 'simple', 'easy', 'start', 'learn'],
  advanced: ['advanced', 'complex', 'optimization', 'optimize', 'improve'],
  realWorld: ['real world', 'practical', 'use case', 'application', 'where'],
  memory: ['memory', 'space', 'storage', 'ram', 'memory usage'],
  stability: ['stable', 'stability', 'preserve', 'order', 'equal elements'],
  inPlace: ['in place', 'in-place', 'constant space', 'o(1) space'],
  recursive: ['recursive', 'recursion', 'recursively'],
  iterative: ['iterative', 'loop', 'iteration', 'iteratively'],
  divideConquer: ['divide', 'conquer', 'divide and conquer', 'split'],
  greedy: ['greedy', 'greedy algorithm', 'local optimum'],
  dynamic: ['dynamic programming', 'memoization', 'dp'],
  followUp: [
    'more',
    'also',
    'additionally',
    'what else',
    'tell me more',
    'continue',
  ],
  clarification: ['what do you mean', 'clarify', 'explain more', 'elaborate'],
  reset: ['reset', 'start over', 'new conversation', 'clear', 'restart'],
};
export const INTENT_PATTERNS = {
  question:
    /^(what|how|why|when|where|which|who|can|could|would|should|is|are|do|does|did)\s/i,
  request:
    /^(please|can you|could you|would you|show me|tell me|explain|help)\s/i,
  comparison:
    /\b(vs|versus|compare|difference|better|worse|faster|slower|than)\b/i,
  complexity: /\b(o\(|big o|complexity|time|space|efficiency|performance)\b/i,
  example: /\b(example|demo|show|demonstrate|sample|instance)\b/i,
  step: /\b(step|process|procedure|how to|algorithm|method)\b/i,
  current: /\b(this|current|now|here|present)\b/i,
  followUp:
    /\b(more|also|additionally|what else|tell me more|continue|and|further)\b/i,
};
